print("hallo selamat datang di bioskop!")
print("dimanakah kamu ingin menonton?")
print("1. XXI Empire")
print("2. XXI Amplas")  
print("3. XXI JCM") 
huruf= input ("masukkan pilihan mu :")
print("mau nonton film apa nih? ada film :")
print("1. Frozen")
print("2. Keramat")  
print("3. KKN di Desa Penari") 
huruf= input ("pilih nomer film :")
print("mau nonton layar bioskop apa :")
print("1. regular")
print("2. dolby almos")  
print("3. premiere ") 
huruf= input("pilih nomer tipe layar :")
huruf= input("mau nonton berapa tiket ?")
print("mau nonton layar bioskop apa :")
print("1. 12.35")
print("2. 14.45")  
print("3. 16.55") 
print("4. 19.05") 
huruf= input("masukkan angka pilihan anda :")
print("oke berhasil, silahkan di nikmati di jam", huruf)